### PR TITLE
Add initial Prometheus metrics to the boltStore

### PR DESCRIPTION
**Pull request by juliusv**
This yields a `/metrics` output like this:

```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.4771e-05
go_gc_duration_seconds{quantile="0.25"} 5.1006e-05
go_gc_duration_seconds{quantile="0.5"} 6.3276e-05
go_gc_duration_seconds{quantile="0.75"} 0.000278633
go_gc_duration_seconds{quantile="1"} 0.004109903
go_gc_duration_seconds_sum 0.007168522
go_gc_duration_seconds_count 13
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 9
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.4816e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 4.3196472e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.453062e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 313803
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 428032
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.4816e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 2.490368e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.2768e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 15568
# HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 5.767168e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.4976339821641476e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 2545
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 329371
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 4800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 47120
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 81920
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.238258e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 524288
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 524288
# HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 9.509112e+06
# HELP message_store_appends_total The total number of messages appended (including append failures) to the message store by topic.
# TYPE message_store_appends_total counter
message_store_appends_total{topic="bar"} 152
message_store_appends_total{topic="baz"} 909
message_store_appends_total{topic="foo"} 194
# HELP message_store_gc_duration_seconds The distribution of message store garbage collection cycle durations in seconds.
# TYPE message_store_gc_duration_seconds histogram
message_store_gc_duration_seconds_bucket{le="0.1"} 12
message_store_gc_duration_seconds_bucket{le="0.5"} 12
message_store_gc_duration_seconds_bucket{le="1"} 12
message_store_gc_duration_seconds_bucket{le="5"} 12
message_store_gc_duration_seconds_bucket{le="10"} 12
message_store_gc_duration_seconds_bucket{le="30"} 12
message_store_gc_duration_seconds_bucket{le="60"} 12
message_store_gc_duration_seconds_bucket{le="120"} 12
message_store_gc_duration_seconds_bucket{le="300"} 12
message_store_gc_duration_seconds_bucket{le="+Inf"} 12
message_store_gc_duration_seconds_sum 0.23178437999999998
message_store_gc_duration_seconds_count 12
# HELP message_store_gets_total The total number of retrieved messages (including retrieval failures) from the message store by topic.
# TYPE message_store_gets_total counter
message_store_gets_total{topic="bar"} 10
message_store_gets_total{topic="foo"} 4
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.27
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.2394496e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.49763387191e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.83824128e+08
```

### CODE REVIEW

**Comment by juliusv** [comment]
@ilackarms

**Comment by ilackarms** [comment]
i'd like to test this one

**Comment by juliusv** [comment]
@ilackarms You mean as in trying it out, or adding tests? Unfortunately, Prometheus metrics are not that well testable at the moment (sort of like logs), since you cannot retrieve the value of individual metrics easily, only via protobuf magic or dumping the entire text or protobuf output and comparing it (while ignoring some series that can't be easily controlled). For normal components that happen to just have instrumentation of their own code, we usually don't add direct tests for the metrics. I did once add metrics tests to some exporters (whose only purpose was producing metrics), like cAdvisor, but it's a bit "meh": https://github.com/google/cadvisor/blob/master/metrics/prometheus_test.go#L218-L242

**Comment by ilackarms** [comment]
hm, understandable. maybe we can just have a test to hit the /metrics endpoint, and verify one of the key-value pairs ?

**Comment by juliusv** [comment]
@ilackarms I added a unit test for the store metrics - as you can see, testing metrics is only possible in a bit of an ugly way at the moment.

**Comment by ilackarms** [comment]
ugly is better than none :)

lgtm

**Comment by juliusv** [comment]
@ilackarms Aaaand of course I had forgotten to check in the metrics fixture file before merging. I allowed myself to just push it to master: https://github.com/juliusv/message-buffer/blob/master/fixtures/store_metrics.txt

**Pull request merged**
